### ISSUE TITLE
Help with running the code

### ISSUE THREAD

**Issue by ghost** [rhodricusack/diffeomorph#3]
Hi,

I am a undergraduate student at Western Sydney University wanting to create controlled scrambled stimulus images for a python coded psychology experiment using your code to create diffeomorphic transformations in MatLabs. My stimulus images are Mooney faces that I have created using a parametric machine model algorithm with JavaScript in VCS from another author. The problem however is that i am very inexperienced at using MatLabs and cannot figure out how to use your code. I have read the associated paper you provided in the GitHub description to try better understanding how the code works however that did not translate into anything helpful when it came down to me actually trying to run the code. Do you have any detailed instructions or tips that could help me use your code? 

Kind regards,
Kiran.

**Comment by rhodricusack** [comment]
Thanks for your interest in the code. How far have you got? Do you Matlab running so you get the >> prompt?

________________________________
From: averagestudentdontfail ***@***.***>
Sent: Thursday 31 March 2022 22:40
To: rhodricusack/diffeomorph ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [rhodricusack/diffeomorph] Help with running the code (Issue #3)


Hi,

I am a undergraduate student at Western Sydney University wanting to create controlled scrambled stimulus images for a python coded psychology experiment using your code to create diffeomorphic transformations in MatLabs. My stimulus images are Mooney faces that I have created using a parametric machine model algorithm with JavaScript in VCS from another author. The problem however is that i am very inexperienced at using MatLabs and cannot figure out how to use your code. I have read the associated paper you provided in the GitHub description to try better understanding how the code works however that did not translate into anything helpful when it came down to me actually trying to run the code. Do you have any detailed instructions or tips that could help me use your code?

Kind regards,
Kiran.

**Comment by ghost** [comment]
Yes when i open it in MatLabs i get a "Command window" at the bottom with >> prompt. Not sure where to go from there however.

**Comment by rhodricusack** [comment]
And can you open the diffeomorph.m file in the editor? You can then either type diffeomorph at the >> prompt or press the green "play" button in the editor.

You'll need to the fix the input filename(s)

Rhodri Cusack
Director, Trinity College Institute of Neuroscience
The Thomas Mitchell Professor of Cognitive Neuroscience
School of Psychology
Trinity College Dublin
Dublin 2
Ireland

Learn about TCIN website<http://www.tcd.ie/neuroscience> video<https://www.tcd.ie/Neuroscience/assets/images/TCIN-Long-Film.mp4> (short<https://www.tcd.ie/Neuroscience/assets/images/TCIN-Short-Film.mp4>) MRI<http://www.tcd.ie/neuroscience/mri>
Overview of my group: www.cusacklab.org<http://www.cusacklab.org/>
Infant fMRI: www.foundcog.org<http://www.foundcog.org/>
Online tasks for infants: baby.cusacklab.org<http://baby.cusacklab.org/>


________________________________

**Comment by averagestudentdontfail** [comment]
Hi, 

I have typed "diffeomorphic" into the >> prompt and there is now a 'output directory' that has been created in the root folder that contains the diffeomorph.m file. A new window seperate to the MatLabs then appears called "Figure 10." I have renamed renamed the outpicpath simply as "output" and the picpath as "input" in the MatLabs editor. I have noticed that after renaming 'output directory' and 'picpath' that in the GitHub Desktop app showed lines 20 and 21 has highlighted in red as shown here:

-picpath='directory with images'
-outpicpath='output directory'

which then changed to being highlighted in green as shown here after making these edits. 
+picpath='input'
+outpicpath='output'

However, i am a bit confused on how i add the picpath 'input' directory with all of my stimulus images into MatLabs to run the the code with? I have tried adding my own 'input' folder with all my stimulus images manually in the root folder via the explorer and then adding it to the MatLabs path via the editor by navigating through <Add to path., and then <Selected folders but this doesnt seem to be the correct way of doing it.

**Comment by averagestudentdontfail** [comment]
I have tried to set values of paths like this:

picpath='C:\Users\send2\OneDrive\Documents\GitHub\diffeomorph\input'
outpicpath='C:\Users\send2\OneDrive\Documents\GitHub\diffeomorph\output'

and have fixed image type for my stimulus images like this:

imgtype='png'; %file type
fns=dir(fullfile(picpath,sprintf('*.png',imgtype)));
figure(10);

I have left all variables at the start of the function as the default values (e.g., maxdistortion=160; % changes max amount of distortion nsteps=40; % number of steps, imsz= 1000) 

Howvever, when i try running the function diffeomorphic i get the error as follows:

Index in position 1 is invalid. Array indices must be positive integers or logical values.

Error in diffeomorphic (line 63)
    Im((x1+1):(x1+Psz(1)),(y1+1):(y1+Psz(2)),:)=P;

**Comment by rhodricusack** [comment]
Hi
Seems like possibly a problem loading the images. Before running, can you type "dbstop if error" (or if you're running from the editor, click on line 63 so that a red stop symbol appears).
Run the code
When it stops, at command line type
>> size(Im)
Best R
________________________________

**Comment by ghost** [comment]
Hi, 

I believe i have gotten your code working for create diffeomorphic transformations for my images. I fixed the path values by making sure not to have any of the folders in the root folder that contains the diffeomorphic.m file. 

I fixed the values for the paths by making it access my local system instead of my onedrive:

picpath='C:\Users\send2\OneDrive\University\Psychology\YEAR TWO\AUTUMN\Perception\Assessments\Scientific Report\Part 1\Stimulus\Processed\Cropped_upright';
outpicpath='C:\Users\send2\OneDrive\University\Psychology\YEAR TWO\AUTUMN\Perception\Assessments\Scientific Report\Part 1\Stimulus\Processed\Distorted';

I also fixed the image file type for my stimulus images for png:

imgtype='png'; %file type
fns=dir(fullfile(picpath,sprintf('*.png',imgtype)));
figure(10);

I have now gotten outputs from both Figure 10 and Figure 11 in seperate screens and i am very happy with how the diffeomorphic transformations turned out in the output folder. Thank you so much for helping me with running your code, it was perhaps my second time actually using MatLabs and i learned a lot from this experience of using someone else's code. Just one question if you do not mind, what do the outputs in Figure 10 signify?
